name: GitHub Pages

on:
  push:
    branches:
      - main  # or 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # uploads all files including index.html

      - uses: actions/configure-pages@v4

      - uses: actions/deploy-pages@v4
